### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/homekit_wifi_thermostat#10]
Hi @maccoylton 

 I would like to share some issues with you that I found.

- Your wiki instruction is old. 
- When the device cooling mode and force to cool, it writes on-screen "OFF", (need to write "COOL")
- Even though the temperature has an integer value, for example, 5, 10, 20, on-screen it says 5.5, 10.5, 20.5. Fraction value stays always even if It was written before. (Try you will see what I am meaning)

Requests:

- Screen UI design is not good. Maybe it can be improved a little bit. 
- According to your UI design on the home app, sorting of OFF-COOL-HEAT-AUTO looks downward like picture 1. It is not useful for especially iPhone users. Picture 2 is more useful. Please try it, and you will see. 
- I suggested that before, you didn't like it. But I almost never use the EVE app and after started to use your thermostat, I always look for the humidity of the room on the main page. Everything is here, just add a new humidity accessory and share the humidity data with them. 

Picture1:

![IMG_3243](https://user-images.githubusercontent.com/38145537/116162228-08888200-a6fe-11eb-8a2c-2f20d4e90e65.PNG)

Picture2:
![IMG_3244](https://user-images.githubusercontent.com/38145537/116162219-01fa0a80-a6fe-11eb-8465-c8fe6ea55c2f.PNG)

**Comment by maccoylton** [comment]
Updated 

- Updated Wiki
- The accessory is only coded to run a central heating system not a full HAVAC, hence the OFF.  I don't have a HAVAC system is not easy for me to enhance and test for that scenario. 
- I'll take a look at the logic around the fractions
- I have no control over the UI that is based on to how those app are coded
- The HomeKit spec doesn't have a way for the accessory to control the sort order of the drop down that I know off, so I have not control over that
- As per previous answer my personal preference is not to add humidity as a separate item

**Comment by okanduzyel** [comment]
Addition: 

Sometimes, the screen stays open and waits until an action which touching buttons or touching the thermostat icon in homekit. I highly recommend that create a task that clears the screen every ten seconds continuously.

**Comment by maccoylton** [comment]
The screen drawing runs in a task, which to avoid fragmentation runs continuously. When the screen is turned on a timer function is used to turn it off, unless of course some further action happens within that timers grace period. There is something not quite right in that logic that determine if it is time to turn the screen off.

**Comment by xrust83** [comment]
Hello, yesterday I also assembled this thermostat and there were a lot of questions, it has no output to the relay, I don’t understand how to virtually insist on turning it on, if the temperature is in homekit, it is hard-coded, then the buttons control it. There is also a question about the temperature, after a reboot the thermostat shows 26 but it is worth changing 25.5 or 26.5 and 0.5 is already always on the screen and does not redraw, it might be better not to remove the discharge and make 25.0 26.0 in this problem I see this problem is over a year old :(   
I want to note that the firmware itself and the response from the home application are very responsive and instant, it's very cool

**Comment by xrust83** [comment]
I found the Peters thermostat https://www.studiopieters.nl/esp8266-homekit-thermostat/, according to the scheme everything is 1 in 1 and the menu is the same, even the connection code is 111-11-111, I hoped that there were transistors on the circuit to control the relay, but this is not so. And in that firmware there is not a stable screen, it constantly hoots and breaks. Maybe there is an option to get a more recent firmware for money :-)

**Comment by maccoylton** [comment]
This  is intended to be used with a secondary device like a Sonoff basic, not to be hard wired to a relay, hence it is called a wireless thermostat. 

I also do a wired version for use with bht-002.

**Comment by xrust83** [comment]
my thermostat works on sonoff th10 on HAA firmware

I figured out how it works.  automation is created in EVE, I played around with the work of the socket, everything works, the question remains of supporting the DS18b20 sensor.  Perhaps you can do an analytical project.  with other sensor, ready to provide any tests

**Comment by maccoylton** [comment]
Latest release should fix screen handling. 

I generally only add features on request where either I have a personal need or there is sponsorship. So I ahve no plans to add DS18b20 at this time

**Comment by xrust83** [comment]
https://www.youtube.com/watch?v=Z8gICt6KM7g
The problem with tenth units is fixed, thanks

Цена вопроса?
How much does it cost

**Comment by xrust83** [comment]
I tried uploading the project and compiling the file, I succeeded, I think I figured out how to draw my design =), maybe I'll deal with Dallas and I will have to remove the humidity icon. It will be difficult to do it manually, but it is possible. if there is a special program for this, please share the name
![IMG_0098](https://user-images.githubusercontent.com/58448955/175367065-54f9549b-42a3-4f15-b3c7-5fa74eca21a1.JPG)

P/S. I was very embarrassed by the dot, I thought it was a marriage of the indicator, now I know that this is a dot-label ;-)

**Comment by xrust83** [comment]
Temperature icon complited
before
![IMG_0103](https://user-images.githubusercontent.com/58448955/175426996-d53aba26-3f47-4b75-ab44-9261ba5d611f.JPG)

after
![IMG_0106](https://user-images.githubusercontent.com/58448955/175426655-43534765-4f71-4617-a7f8-1de97a5b3992.JPG)
