### ISSUE TITLE
build firmware

### ISSUE THREAD

**Issue by GWan1234** [maccoylton/homekit_wifi_thermostat#11]
How to build the firmware and what platform to use? esp-if or esp-open-sdk or arduino? 

Can you tell me how to build it? ?

**Comment by maccoylton** [comment]
If you want to make your own modifications then you will need to set up a build environment, take a look at the intructionsm which will help you set up and environent :- https://github.com/maximkulkin/esp-homekit-demo/wiki/Build-instructions-ESP8266

You don't have to buld the code yourself, if you just want to run the firmware then follow the instructons in the Wiki to get the firmware onto your device.
