### ISSUE TITLE
support upgrade from the local web server?

### ISSUE THREAD

**Issue by GWan1234** [maccoylton/homekit_wifi_thermostat#12]
Does it support upgrading main.bin from the local web server, because I can't get the file through github. I built a local web server using nginx.

**Comment by GWan1234** [comment]
Or to build a firmware that can be used directly, only need to flash it through ttl, don't need to use github to upgrade it.

**Comment by maccoylton** [comment]
What's your issue with GitHub?

**Comment by GWan1234** [comment]
I have given up my idea. thank you for your reply.
