### ISSUE TITLE
nodemcu where connect sensor, display and button?

### ISSUE THREAD

**Issue by lizzus** [maccoylton/homekit_wifi_thermostat#3]
hi, i'm using a nodemcu (https://alselectro.files.wordpress.com/2017/10/nodemcu_pins1.jpg). where i must connect sensor? on .c file i read Pin4... but i don't understand.
thanks for help

**Comment by lizzus** [comment]
themp is on D2

**Comment by lizzus** [comment]
only a question... i not understand why refresh regulary and show home logo...

**Comment by lizzus** [comment]
i don't know where connect relay.

**Comment by maccoylton** [comment]
The screen refresh was to avoid screen burnout.

This is a wireless thermostat,. i.e. the connection to the relay is wireless and done through HomeKit automation, this is covered in the realm

The connections are as follows:-
4 - DH22
12 - Temperature UP 
13 - Temperature Down
0 - Reset
2 - LED
14 - SSD1306 SCL_PIN
5 - SSD1306 SDA_PIN
