### ISSUE TITLE
use a Rotary Encoder KY-040 for up/down temperature

### ISSUE THREAD

**Issue by lizzus** [maccoylton/homekit_wifi_thermostat#4]
I tried a Rotary Encoder KY-040 for change up and down temperature witha rotation to right or to left. If Rotary Encoder KY-040 pushed change from off to heat. I don't know if some parte of code must be changed, because Rotary Encoder KY-040 is not perfect and sometimes loss some pulse. What do you think?

**Comment by maccoylton** [comment]
I suspect we'd need to come up with a better way of using this controller rather than the button library I;m using at the moment.

**Comment by lizzus** [comment]
What do you mean? 
Thanks for answer.

**Comment by maccoylton** [comment]
I've changed to use a different library for handling button, not sure if this will make a different, but give it a try.

**Comment by maccoylton** [comment]
Closed as no response to last question
