### ISSUE TITLE
Version and name

### ISSUE THREAD

**Issue by Kristian8606** [maccoylton/homekit_wifi_thermostat#6]
Do you know why these parameters are no longer displayed and how do I fix this?

![CF77E4F8-CACC-4265-A7DD-173B92D88517](https://user-images.githubusercontent.com/34716572/63928459-3ebcbc80-ca58-11e9-8ca4-bd2a476205d9.jpeg)

**Comment by maccoylton** [comment]
Which app are you using on the IOS device and which version of IOS? On mine these values still show ok
![image](https://user-images.githubusercontent.com/2248641/63982754-b5d76c80-cabb-11e9-8465-a9e3281623a7.png)

**Comment by Kristian8606** [comment]
I'm using IOS 13 beta with application home,
I flash your example through ОТА.

**Comment by Kristian8606** [comment]
>>> wifi_config: Initializing WiFi config
!!! wifi_config: No configuration found
>>> wifi_config: Starting AP mode
>>> wifi_config: Starting DHCP server
manuf='manuf_unknown' serial='DC:4F:22:19:9D:17' model='model_unknown' revision='0.0.0' c#=0
mode : sta(dc:4f:22:19:9d:17) + softAP(de:4f:22:19:9d:17)
add if0
add if1
bcn 100
>>> wifi_config: Starting WiFi scan
scandone

**Comment by maccoylton** [comment]
Are you sure this is the correct part of the log, the log above show you in the initial set-up which would be before the firmware is flashed,  .. note where it says  entering AP mode. If it were later ion the process it would not be entering AP mode

BTW I checked on IOS 13 Beta and it looks fin for me

![image](https://user-images.githubusercontent.com/2248641/64074804-16c39800-cca8-11e9-88bb-4c93f19d0e39.png)

**Comment by Kristian8606** [comment]
I took this part of the log before pairing the device but even after successful pairing the situation is still the same

**Comment by Kristian8606** [comment]
I'm using LCM version 1.0.0

**Comment by maccoylton** [comment]
Do you have an IOS12 device? Could you try removing and re-pairing for an IOS12 device, just a guess but maybe something in IOS13 causing it.

**Comment by Kristian8606** [comment]
I have another device with ios 12 but the problem didn't resolve.

**Comment by maccoylton** [comment]
Is the thermostat working ok although these fields are blank?

**Comment by Kristian8606** [comment]
yes work without problem

**Comment by maccoylton** [comment]
have not been able to re-produce this issue, mine continues to work fine through a couple of iterations
