### ISSUE TITLE
Temperature pooling time 

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/homekit_wifi_thermostat#8]
Hi,

Temperature pooling time is too long. Could you decrease it to 5000? (5sec)

TEMPERATURE_POLL_PERIOD 30000 -> **TEMPERATURE_POLL_PERIOD 5000**

**Comment by maccoylton** [comment]
HI curious why do you need such speedy reaction? It's unlikley a room will change +- 0.2 in less than 30 seconds. If we trigger the heating system on and off too often it can cause damage to your heating system.

**Comment by okanduzyel** [comment]
I have an electrical heating system in my home. Actually, Not only in 5 seconds, and also, I can trigger it even 50hz in a second, no problem for it. But If It's a problem for other people, 30 seconds of pooling time should stay.

**Comment by maccoylton** [comment]
In my case I use a gas central heating system, and they defiantly don't like being turned on/off to often. If it were a big deal I could add an extra characteristics to allow this to be tuned, but for now I think 30 seconds is a simple and easy compromise
