### ISSUE TITLE
Humidity sensor 

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/homekit_wifi_thermostat#9]
Hi,

I don't have ssd1306 yet. Thus, I can't try the code because it gives a screen init error at the initiation. 

Does it have a separated humidity sensor as I shown below?

<img width="122" alt="Ekran Resmi 2021-03-21 15 26 36" src="https://user-images.githubusercontent.com/38145537/111904834-dd08dc80-8a59-11eb-8316-ab80362e5d94.png">

**Comment by okanduzyel** [comment]
Yes, I have got ssd1306 and tried the project. 

![IMG_3167](https://user-images.githubusercontent.com/38145537/112856489-82562d00-90b8-11eb-87dc-748bb387eeac.PNG)




Unfortunately, there is no individual humidity sensor accessory. Could you add separate humidity sensor for it? 

```
HOMEKIT_SERVICE(HUMIDITY_SENSOR, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Humidity Sensor"),
            &humidity,
            NULL
        }),
```

**Comment by maccoylton** [comment]
I didn't want to show humidity as a separate service, but as a characteristic of the thermosmtat.  You can see this through the eve app.

**Comment by okanduzyel** [comment]
<img width="233" alt="Ekran Resmi 2021-03-29 19 11 04" src="https://user-images.githubusercontent.com/38145537/112886726-f9042200-90da-11eb-9040-c98cef563be4.png">

It is really helpful and also can see abruptly on the main screen with adding favorite.

**Comment by maccoylton** [comment]
I understand, but I find having multiple services for each accessory can get quickly get difficult to manage particularly when you have lots of accessories.  I prefer it the way it is today.  This is not a bug but personal preference
